## Preprocessing

In [54]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [55]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df= application_df.drop(["EIN","SPECIAL_CONSIDERATIONS"],axis='columns')
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,36500179,0

In [56]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                19568
APPLICATION_TYPE       17
AFFILIATION             6
CLASSIFICATION         71
USE_CASE                5
ORGANIZATION            4
STATUS                  2
INCOME_AMT              9
ASK_AMT              8747
IS_SUCCESSFUL           2
dtype: int64

In [57]:
name_counts = application_df["NAME"].value_counts()
# Look at NAME value counts to identify and replace with "Other"
NAME_to_replace = list(name_counts[name_counts < 5].index)
# Replace in dataframe
for nam in name_counts:
    application_df['NAME'] = application_df['NAME'].replace(nam,"Other")
# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [58]:
application_counts = application_df["APPLICATION_TYPE"].value_counts()

In [59]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_types_to_replace = list(application_counts[application_counts < 500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")
# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [60]:
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [61]:
classification_counts[classification_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [62]:
classification_counts[classification_counts > 10]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: count, dtype: int64

In [63]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"

classification_types_to_replace = list(classification_counts[classification_counts < 1000].index)
# Replace in dataframe
for cls in classification_types_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [64]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,NAME_13TH BOMB SQUADRON ASSOCIATION,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,1,108590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,1,6692,1,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,1,142590,1,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34296,1,5000,0,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34298,1,36500179,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [65]:
# Split our preprocessed data into our features and target arrays

X = application_dummies_df.drop(['IS_SUCCESSFUL'],axis=1).values
y = application_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
# Split the preprocessed data into a training and testing dataset

In [66]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [67]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()
number_input_features = len(X_train[0])

# First hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation="relu", input_dim=number_input_features))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=70, activation="tanh"))
# Third layer
nn.add(tf.keras.layers.Dense(units=50, activation="tanh"))
#Fourth Layer
nn.add(tf.keras.layers.Dense(units=30, activation="tanh"))
#Fifth Layer
nn.add(tf.keras.layers.Dense(units=10, activation="tanh"))
#Output Layer
nn.add(tf.keras.layers.Dense(units=1, activation="tanh"))

# Check the structure of the Sequential model
nn.summary()

c:\Users\harit\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 100)            │     1,961,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 70)             │         7,070 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 50)             │         3,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 10)             │           310 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,973,471 (7.53 MB)

 Trainable params: 1,973,471 (7.53 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [69]:
# Train the model
#fit_model = nn.fit(X_train_scaled, y_train, epochs=100)
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
fit_model = nn.fit(X_train_scaled, y_train, 
                 epochs=100, 
                 batch_size=32)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.7233 - loss: 0.6361
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9429 - loss: 0.1917
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9405 - loss: 0.1525
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9618 - loss: 0.1714
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9610 - loss: 0.1089
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9616 - loss: 0.1034
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9641 - loss: 0.0967
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9629 - loss: 0.1077
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9629 - loss: 0.0978
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9648 - loss: 0.0947
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9657 - loss: 0.0926
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9609 - loss: 0.1051
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9632 - loss: 0.1062
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.9628 - loss: 0.0959
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9632 - loss: 0.1015
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9616 - loss: 0.1126
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9628 - loss: 0.3538
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9640 - loss: 0.1733
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9631 - loss: 0.1351
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9644 - loss: 0.1495
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9630 - loss: 0.1385
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9618 - loss: 0.1698
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9566 - loss: 0.2748
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9597 - loss: 0.1563
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9627 - loss: 0.1258
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9640 - loss: 0.1331
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9659 - loss: 0.1084
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9639 - loss: 0.1186
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9624 - loss: 0.2217
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9638 - loss: 0.2608
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9587 - loss: 0.2451
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9657 - loss: 0.2392
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9620 - loss: 0.2895
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9643 - loss: 0.2758
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9636 - loss: 0.2943
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9640 - loss: 0.2790
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9610 - loss: 0.1340
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9626 - loss: 0.1342
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9625 - loss: 0.1093
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9639 - loss: 0.1213
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.9642 - loss: 0.1355
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9626 - loss: 0.1176
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - accuracy: 0.9638 - loss: 0.1148
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.9639 - loss: 0.2590
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9628 - loss: 0.1484
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9618 - loss: 0.1069
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9634 - loss: 0.1301
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9648 - loss: 0.1119
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9653 - loss: 0.0947
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9621 - loss: 0.1263
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - accuracy: 0.9639 - loss: 0.1154
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.9646 - loss: 0.0986
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.9627 - loss: 0.1057
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.9650 - loss: 0.1014
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9632 - loss: 0.0988
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9626 - loss: 0.1039
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9628 - loss: 0.1188
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9639 - loss: 0.1072
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9632 - loss: 0.1018
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9634 - loss: 0.1049
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.9633 - loss: 0.1012
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9620 - loss: 0.1264
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9590 - loss: 0.2800
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9633 - loss: 0.1771
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 16s 19ms/step - accuracy: 0.9638 - loss: 0.1357
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9643 - loss: 0.1094
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9655 - loss: 0.1041
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9644 - loss: 0.1065
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9649 - loss: 0.1019
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9640 - loss: 0.1188
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9609 - loss: 0.1254
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9647 - loss: 0.1204
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9662 - loss: 0.1121
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9650 - loss: 0.1139
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9642 - loss: 0.1057
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9643 - loss: 0.1121
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9632 - loss: 0.1187
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9656 - loss: 0.1079
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9656 - loss: 0.1131
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9655 - loss: 0.1049
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9620 - loss: 0.1159
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9648 - loss: 0.1068
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9641 - loss: 0.1169
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9636 - loss: 0.1147
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9640 - loss: 0.1184
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9648 - loss: 0.1127
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9630 - loss: 0.1162
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9642 - loss: 0.1175
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9639 - loss: 0.1264
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9641 - loss: 0.1126
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9626 - loss: 0.1144
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9643 - loss: 0.1279
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9637 - loss: 0.1058
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9636 - loss: 0.1232
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9613 - loss: 0.1094
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9634 - loss: 0.1290
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9633 - loss: 0.1620
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9635 - loss: 0.2033
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9638 - loss: 0.1249
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9654 - loss: 0.1156

In [70]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 3ms/step - accuracy: 0.7875 - loss: 0.5356
Loss: 0.5355668067932129, Accuracy: 0.7875218391418457

In [71]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

The report should contain the following:

Overview of the analysis: Explain the purpose of this analysis.
The purpose of the analysis is to help the nonprofit foundation Alphabet Soup to select the applicants for funding with the best chance of success in their ventures. 

Data Preprocessing

What variable(s) are the target(s) for your model?
IS_SUCCESSFUL is the target.
What variable(s) are the features for your model?
all the variables other than IS_SUCCESSFUL.
What variable(s) should be removed from the input data because they are neither targets nor features?
EIN and SPECIAL CONSIDERATIONS had to be removed.
Compiling, Training, and Evaluating the Model

How many neurons, layers, and activation functions did you select for your neural network model, and why?
Were you able to achieve the target model performance?
What steps did you take in your attempts to increase model performance?
Removed EIN and SPECIAL CONSIDERATIONS FIELDS.
increased the hidden layers and combination of neurons
checked elu,tanh,sigmoid,relu. Settled to tanh. 

Summary: Summarize the overall results of the deep learning model. Include a recommendation for how a different model could solve this classification problem, and then explain your recommendation.